name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_application:

    runs-on: ubuntu-latest
    env:
      SOLUTION_FOLDER: UgcsPPK
      APP_FOLDER: App
      APP_NAME: ugcs-ppk
      TESTS_FOLDER: Tests
      PUBLISH_FOLDER: output
      ARTIFACT_NAME: ugcs-ppk
      VIEWS_FOLDER: ugcs-ppk
      DISPLAY_NAME: UgCS-PPK
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Generate build number
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}  
    - name: Run Tests
      run: |
        cd $SOLUTION_FOLDER/$TESTS_FOLDER
        dotnet test
    - name: Build
      run: |
        cd $SOLUTION_FOLDER
        dotnet restore
        cd $APP_FOLDER
        VERSION=$(grep 'Version' App.csproj | awk -F">" '{print $2}' | awk -F"<" '{print $1}')
        cd $VIEWS_FOLDER
        sed -i 's#Title="$DISPLAY_NAME"#Title="$DISPLAY_NAME '$VERSION.$BUILD_NUMBER'"#g' MainWindow.xaml
        cd ../
        mkdir $PUBLISH_FOLDER
        dotnet publish -c Release -r win10-x64 -o $PUBLISH_FOLDER/
        cd $PUBLISH_FOLDER
        ARTIFACT_NAME=$APP_NAME-$VERSION.$BUILD_NUMBER
        zip -r ../$ARTIFACT_NAME.zip *
    - name: Uploading artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: UgcsPPK/App/*.zip

  build_documentation:
    runs-on: ubuntu-latest
    container: docker://ugcs/doker:latest 
    steps:
    - uses: actions/checkout@v2
    - name: Creating documentation
      run: |
        chmod +x ./Documentation/scripts/generate-pdf.sh
        ./Documentation/scripts/generate-pdf.sh
    - name: Uploading artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ugcs-ppk-documentation
        path: Documentation/pdf/*.pdf
    


      